#spring:
#  security:
#    oauth2:
#      client:
#        registration:
#          avanpost:
#            clientId: cdi_kazna
#            clientSecret: 8wAY1VfYhX8qxpShCaxI4qI3EMgV3WQC
#            redirect-uri: http://localhost:8080/login/oauth2/avanpost
##            redirect-uri: http://localhost:8080/welcome
#            authorization-grant-type: authorization_code
#            scope: openid
#        provider:
#          avanpost:
#            authorization-uri: http://localhost:8091/realms/cdi_kazna_realm/protocol/openid-connect/auth
#            token-uri: http://localhost:8091/realms/cdi_kazna_realm/protocol/openid-connect/token
#            user-info-uri: http://localhost:8091/realms/cdi_kazna_realm/protocol/openid-connect/userinfo
#            user-name-attribute: preferred_username
#
## http://localhost:8091/realms/master/.well-known/openid-configuration